# 기본 설정
port 6380
bind 0.0.0.0
daemonize no
supervised systemd
dir /data

# 복제 설정
replicaof redis-master 6379
masterauth redis_password

# 보안 설정
requirepass redis_password

# 퍼시스턴스 설정
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# 메모리 설정
maxmemory 1gb
maxmemory-policy allkeys-lru
maxmemory-samples 5
