apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-kustomize
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      managed-by: kustomize
    includeSelectors: true
