shared_preload_libraries = 'pg_stat_statements'
shared_buffers = '1GB'
work_mem = '64MB'
maintenance_work_mem = '256MB'
effective_cache_size = '3GB'
synchronous_commit = off
max_connections = 100
random_page_cost = 1.1
effective_io_concurrency = 200
wal_level = logical
max_wal_size = '1GB'
pg_stat_statements.max = 10000
pg_stat_statements.track = all
