apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-image
  namespace: k8s-study
  labels:
    app: broken-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-image
  template:
    metadata:
      labels:
        app: broken-image
    spec:
      containers:
        - name: nginx
          image: nginx:this-tag-does-not-exist-k8s-study
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

