apiVersion: v1
kind: ConfigMap
metadata:
  name: capstone-web-config
  namespace: k8s-capstone
data:
  APP_ENV: capstone
  LOG_LEVEL: info
---
apiVersion: v1
kind: Secret
metadata:
  name: capstone-web-secret
  namespace: k8s-capstone
type: Opaque
stringData:
  API_TOKEN: replace-in-real-environment

