apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: capstone-web-ingress
  namespace: k8s-capstone
spec:
  podSelector:
    matchLabels:
      app: capstone-web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: k8s-capstone
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080

