# mongod.conf (MongoDB Custom Configuration)
# 실무 환경에 맞춰 세부 튜닝 가능.

# net:
  port: 27017
  bindIp: 0.0.0.0   # 컨테이너 내부뿐만 아니라 외부 접근도 가능하도록 설정

# storage:
  dbPath: /data/db
  journal:
    enabled: true

# systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# processManagement:
  fork: false

# security:
  # authorization: enabled   # 인증을 사용하려면 아래와 같이 설정
