apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-echo-from-labeled-pods
  namespace: k8s-study
spec:
  podSelector:
    matchLabels:
      app: echo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: allowed
      ports:
        - protocol: TCP
          port: 8080

