spring:
  profiles:
    active: local
server:
  port: ${SERVER_PORT:8080}
logging:
  file:
    name: ./logs/app.log
    path: ./logs
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: production