apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: k8s-study
  labels:
    app: hello-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
          name: http

